---
- hosts: localhost
  vars:
   vra_host: "{{ lookup('env', 'VRA_HOST') }}"
   vra_user: "{{ lookup('env', 'VRA_USER') }}"
   vra_pass: "{{ lookup('env', 'VRA_PASS') }}"
   create: false
   delete: false
   deployment_name: Test_Ansible

  tasks:
  - name: Acquire auth token
    ansible.builtin.uri:
      url:  "https://{{ vra_host }}/csp/gateway/am/api/login"
      method: POST
      body_format: json
      body: 
        username: "{{ vra_user }}"
        password: "{{ vra_pass }}"
      validate_certs: no
      return_content: yes
    register: token
   
  - name: List all current deployments
    ansible.builtin.uri:
      url: "https://{{ vra_host }}/deployment/api/deployments"
      method: GET
      headers:
        authorization: "Bearer {{ token.json['cspAuthToken'] }}"
      validate_certs: no
      return_content: yes
    register: deploys

  - set_fact:
      deployment_id: "{{ deploys.json.content | selectattr('name', 'match', deployment_name) | map(attribute='id') | join }}"

  - debug:
      msg: "{{ deployment_id }}"

  - name: Delete deployment
    ansible.builtin.uri:
      url: "https://{{ vra_host }}/deployment/api/deployments/e7232719-9d1e-47b4-99bb-65f09cef0815"
      method: DELETE
      headers:
        authorization: "Bearer {{ token.json['cspAuthToken'] }}"
      validate_certs: no
      return_content: yes
    when: delete == 'true'
